version: '3'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
    ports:
      - "5001:5000" 
    environment:
      - MONGO_URI=mongodb://mongodb:27017/edu-game
      - CORS_ORIGIN=http://localhost:3000
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - './data:/data/db'
    ports:
      - "27017:27017"

# http://127.0.0.1:5000
# is this valid from frontend?
# which address should be used?
# http://localhost:5000